### PR TITLE
Fix crashing Android Example

### PR DESCRIPTION
**Pull request by hiaw**
using the same implementation as vision-camera-ocr ensures the example works in android

Screenshot_20220525-112151_VisionCameraCodeScanner Example
d

### CODE REVIEW

**Comment by jorgebrunetto** [comment]
Fixed in https://github.com/jorgebrunetto/vision-camera-code-scanner

**Comment by ducpt-bili** [comment]
Thank @jorgebrunetto, it work for me.

**Comment by chj-damon** [comment]
it works for me.

**Comment by hiaw** [comment]
- [ ]

**Pull request closed without merging**
