### PR TITLE
Barcode was using incorrect import paths

### PR DESCRIPTION
**Pull request by hiaw**
causing crashes when combined with MLKit Text Recognition

### CODE REVIEW

**Comment by brooowarrr** [comment]
hi. I have exactly the same problem when combined with MLKit Text Recognition. strongly suggest to merge this PR and release new version as soon as possible.

**Comment by vitormomberg** [comment]
Hi, could you merge this PR, please?
I have the same issue.

**Comment by cunhamuril** [comment]
Hi, could you merge this PR, please?
I have the same issue.

**Comment by jorgebrunetto** [comment]
Could do the merge this issue, is very important for all.

**Review by jorgebrunetto — APPROVED** [review]

**Comment by ArneV94** [comment]
We are having the same problem, getting this merged would help out. Thanks @jorgebrunetto for the temporary solution!

**Pull request closed without merging**
